'use strict';
const path = require('path'), fs = require('fs'), vm = require('vm');
const { createEnv } = require('./gas-mock.cjs');
const SRC = path.join(__dirname, '..', 'src');
const env = createEnv(SRC), { ctx, state } = env;
let pass = 0, failN = 0;
const ok = (c, m) => { if (c) pass++; else { failN++; console.log('  FAIL: ' + m); } };
const section = t => console.log('\n# ' + t);
const eq = (a, b, m) => ok(a === b, m + ' (expected ' + JSON.stringify(b) + ', got ' + JSON.stringify(a) + ')');
const as = email => { state.active = email; };
const call = (a, p) => { const r = ctx.api(a, p || {}, 'test'); return r; };
const good = (a, p, m) => { const r = call(a, p); ok(r.ok, (m || a) + ' should succeed: ' + (r.error || '')); return r.data; };
const bad = (a, p, re, m) => { const r = call(a, p); ok(!r.ok && (!re || re.test(r.error)), (m || a) + ' should fail' + (re ? ' with ' + re : '') + ' - got ' + JSON.stringify(r).slice(0, 200)); return r; };
const pdfB64 = Buffer.from('%PDF-1.4 test content').toString('base64');
const doc = (over) => Object.assign({ fileName: 'x.pdf', base64: pdfB64 }, over);

section('Public surface (google.script.run exposure)');
const allowed = ['doGet', 'api', 'setupAMLSystem', 'installTriggers', 'dailyMaintenance', 'seedTestData', 'removeTestData', 'AppError'];
const src = env.files.map(f => fs.readFileSync(path.join(SRC, f), 'utf8')).join('\n');
const pub = [...src.matchAll(/^function\s+([A-Za-z0-9_$]+)/gm)].map(m => m[1]).filter(n => !n.endsWith('_'));
ok(pub.every(n => allowed.includes(n)), 'unexpected public functions: ' + pub.filter(n => !allowed.includes(n)).join(','));

section('Setup');
as('owner@firm.test');
const summary = ctx.setupAMLSystem();
ok(summary.warnings.length === 0, 'setup warnings: ' + summary.warnings.join('|'));
const dbId = state.props.DB_SPREADSHEET_ID, ss = env.spreadsheets[dbId];
ok(['Users', 'Companies', 'Engagements', 'UBOs', 'Shareholders', 'Documents', 'KYC_Reviews', 'Risk_Assessments', 'Audit_Log', 'Settings'].every(n => ss.getSheetByName(n)), 'all sheets');
const rootCount = env.driveRoot.children.length;
const s2 = ctx.setupAMLSystem();
eq(env.driveRoot.children.length, rootCount, 'setup idempotent (root folders)');
eq(env.spreadsheets && Object.keys(env.spreadsheets).length, 1, 'setup idempotent (spreadsheets)');
eq(ss.sheets.length, 11, 'setup idempotent (sheets)');
as('mallory@evil.test'); bad('bootstrap', {}, /Access Denied/, 'unregistered user');
as('owner@firm.test'); bad('setupAMLSystem', {}, null, 'n/a');  // api rejects unknown action
as('someone@firm.test'); let threw = false; try { ctx.setupAMLSystem(); } catch (e) { threw = true; } ok(threw, 'non-owner cannot run setup');

section('Users');
as('owner@firm.test');
const boot = good('bootstrap');
eq(boot.user.Role, 'System Administrator', 'initial admin');
const mk = (n, e, r) => good('userSave', { Name: n, Email: e, Role: r, Status: 'Active', Department: 'X' });
mk('Mlro', 'mlro@firm.test', 'MLRO'); mk('Dmlro', 'dmlro@firm.test', 'DMLRO'); mk('Aud One', 'aud1@firm.test', 'Auditor');
mk('Aud Two', 'aud2@firm.test', 'Auditor'); mk('View', 'view@firm.test', 'Viewer');
bad('userSave', { Name: 'Dup', Email: 'AUD1@firm.test', Role: 'Auditor', Status: 'Active' }, /already exists/, 'duplicate user');
as('aud1@firm.test'); bad('userList', {}, /permission/, 'auditor cannot list users');
bad('userSave', { Name: 'x', Email: 'x@firm.test', Role: 'MLRO' }, /permission/, 'auditor cannot create users');
as('dmlro@firm.test'); bad('userSave', { Name: 'Evil', Email: 'e@firm.test', Role: 'System Administrator', Status: 'Active' }, /permission/, 'DMLRO cannot grant privileged role');
good('userSave', { Name: 'Aud Three', Email: 'aud3@firm.test', Role: 'Auditor', Status: 'Active' }, 'DMLRO creates auditor');
as('mlro@firm.test'); const a3 = ctx.dbAll_('Users').find(u => u.Email === 'aud3@firm.test'); good('userSave', { id: a3.UserID, Role: 'Viewer' }, 'MLRO changes a role');
as('owner@firm.test'); bad('userSave', { id: boot.user && ctx.dbAll_('Users')[0].UserID, Status: 'Inactive' }, /own role|retain/, 'admin cannot deactivate self');

section('Companies');
as('aud1@firm.test');
const base = { LegalName: 'Alpha Trading W.L.L.', QFCNumber: 'QFC-100', CRNumber: 'CR-2001', CountryOfIncorporation: 'Qatar', CompanyStatus: 'Active' };
bad('companyCreate', { LegalName: 'NoIds', CountryOfIncorporation: 'Qatar', CompanyStatus: 'Active' }, /QFC number or a CR/, 'needs QFC or CR');
bad('companyCreate', { CountryOfIncorporation: 'Qatar' }, /Legal Company Name is required/, 'required field');
bad('companyCreate', Object.assign({}, base, { DateOfIncorporation: '2026-02-31' }), /valid date/, 'invalid date');
bad('companyCreate', Object.assign({}, base, { ContactEmail: 'nope' }), /valid email/, 'invalid email');
const c1 = good('companyCreate', base).company; const C1 = c1.CompanyID;
eq(C1, 'CMP-000001', 'company ID format'); ok(!('FolderID' in c1), 'folder id not exposed');
const stored = ctx.dbGet_('Companies', C1);
ok(!!stored.FolderID, 'folder id stored in DB');
const folder = env.nodes[stored.FolderID];
ok(folder && folder.name.startsWith('CMP-000001_'), 'company folder created');
eq(folder.children.map(c => c.name).join('|'), 'Corporate Documents|Ownership & UBO|Identification Documents|Financial Documents|Tax Documents|Engagement Documents|Other Documents|Review & Approval', 'subfolders');
bad('companyCreate', Object.assign({}, base, { CRNumber: 'CR-9', LegalName: 'Different' }), /QFC number already registered/, 'dup QFC');
bad('companyCreate', Object.assign({}, base, { QFCNumber: 'QFC-9', CRNumber: 'cr 2001', LegalName: 'Different' }), /CR number already registered/, 'dup CR normalised');
bad('companyCreate', { LegalName: 'ALPHA TRADING LLC', QFCNumber: 'Q9', CountryOfIncorporation: 'Qatar', CompanyStatus: 'Active' }, /Company already exists/, 'dup name');
eq(good('companyList', {}).total, 1, 'list'); eq(good('search', { q: 'alpha' }).rows.length, 1, 'search by name'); eq(good('search', { q: 'QFC-100' }).rows.length, 1, 'search by QFC');
good('companyUpdate', { id: C1, TradingName: 'Alpha' }, 'auditor edits own');
as('view@firm.test'); bad('companyCreate', Object.assign({}, base, { QFCNumber: 'Q77', CRNumber: 'C77', LegalName: 'Zed' }), /permission/, 'viewer cannot create');
bad('companyUpdate', { id: C1, TradingName: 'X' }, /permission/, 'viewer cannot edit');
bad('companyDelete', { id: C1, reason: 'x' }, /permission/, 'viewer cannot delete');
as('aud1@firm.test'); bad('companyDelete', { id: C1, reason: 'x' }, /permission/, 'auditor cannot delete company');
bad('companyGet', { id: 'CMP-999999' }, /not found/, 'unknown company');

section('Engagements / UBOs / ownership');
const eng = good('engagementSave', { CompanyID: C1, EngagementType: 'Audit', StartDate: '2026-01-01', EndDate: '2026-12-31', AssignedAuditor: 'aud1@firm.test', RiskLevel: 'High' }).record;
eq(eng.RiskLevel, 'Not Rated', 'auditor cannot set engagement risk level');
good('engagementSave', { CompanyID: C1, EngagementType: 'Tax', StartDate: '2026-02-01' }, 'multiple engagements');
bad('engagementSave', { CompanyID: C1, EngagementType: 'Audit', StartDate: '2026-05-01', EndDate: '2026-01-01' }, /before the start/, 'end < start');
bad('engagementSave', { CompanyID: C1, EngagementType: 'Bogus', StartDate: '2026-05-01' }, /invalid value/, 'engagement type list');
const u1 = good('uboSave', { CompanyID: C1, FullName: 'Person One', Nationality: 'Testland', OwnershipPercentage: 60, DirectIndirect: 'Direct', QIDNumber: '12345678901', RiskRating: 'Low' }).record;
eq(u1.RiskRating, 'Not Rated', 'auditor cannot set UBO risk rating');
bad('uboSave', { CompanyID: C1, FullName: 'Bad', Nationality: 'X', OwnershipPercentage: 120 }, /must not exceed 100/, 'percentage > 100');
bad('uboSave', { CompanyID: C1, FullName: 'Bad', Nationality: 'X', OwnershipPercentage: 10, QIDNumber: '123' }, /11 digits/, 'QID format');
const r2 = good('uboSave', { CompanyID: C1, FullName: 'Person Two', Nationality: 'Testland', OwnershipPercentage: 55, DirectIndirect: 'Direct' });
ok(r2.warnings.some(w => /exceeds 100/.test(w)), 'UBO total warning');
const cg = good('companyGet', { id: C1 }); eq(cg.ubos.length, 2, 'multiple UBOs'); eq(cg.engagements.length, 2, 'engagements listed');
good('uboSave', { id: u1.UBOID, Notes: 'edited' }, 'edit UBO');
// ownership chain
const holdco = good('shareholderSave', { CompanyID: C1, ShareholderName: 'Holdco Ltd', EntityType: 'Entity', HoldingPercentage: 100, Country: 'Cayman' }).record;
const p1 = good('shareholderSave', { CompanyID: C1, ShareholderName: 'Person One', EntityType: 'Individual', HoldingPercentage: 60, HeldThroughID: holdco.ShareholderID, UBOID: u1.UBOID });
good('shareholderSave', { CompanyID: C1, ShareholderName: 'Big Owner', EntityType: 'Individual', HoldingPercentage: 40, HeldThroughID: holdco.ShareholderID });
let own = good('companyGet', { id: C1 }).ownership;
eq(own.directTotal, 100, 'direct total'); eq(own.chains.length, 2, 'two chains');
eq(own.chains[0].effective, 60, 'effective %');
ok(own.warnings.some(w => /Big Owner.*not recorded as a UBO/.test(w)), 'unrecorded UBO above threshold warned: ' + own.warnings.join('|'));
bad('shareholderSave', { id: holdco.ShareholderID, HeldThroughID: p1.record.ShareholderID }, /individual|circular/i, 'cycle / individual parent');
bad('shareholderDelete', { id: holdco.ShareholderID, reason: 'x' }, /Remove or re-assign/, 'delete entity with holders');
good('shareholderSave', { CompanyID: C1, ShareholderName: 'Solo', EntityType: 'Individual', HoldingPercentage: 10 });
own = good('companyGet', { id: C1 }).ownership; ok(own.warnings.some(w => /110%|expected 100%/.test(w)), 'direct total != 100 warns');

section('Documents');
as('aud1@firm.test');
bad('docUpload', doc({ companyId: C1, docType: 'Passport', fileName: 'evil.exe' }), /not supported/, 'ext rejected');
bad('docUpload', doc({ companyId: C1, docType: 'Passport', fileName: 'fake.pdf', base64: Buffer.from('MZ not a pdf').toString('base64') }), /does not match/, 'magic bytes');
bad('docUpload', doc({ companyId: C1, docType: 'Passport', base64: Buffer.alloc(11 * 1024 * 1024, 65).toString('base64') }), /size exceeds/, 'size limit');
bad('docUpload', doc({ companyId: C1, docType: 'Nope' }), /valid document type/, 'doc type');
const d1 = good('docUpload', doc({ companyId: C1, docType: 'Commercial Registration (CR)', fileName: 'CR_2025.pdf', expiryDate: '2030-01-01' })).document;
ok(!('DriveFileID' in d1), 'file id not exposed');
const d2 = good('docUpload', doc({ companyId: C1, docType: 'Commercial Registration (CR)', fileName: 'CR_2026.pdf', expiryDate: '2031-01-01' })).document;
let dl = good('docList', { companyId: C1 });
eq(dl.documents.find(d => d.DocumentID === d1.DocumentID).VersionStatus, 'Superseded', 'old CR superseded');
eq(dl.documents.find(d => d.DocumentID === d2.DocumentID).VersionStatus, 'Current', 'new CR current'); eq(d2.VersionNo, 2, 'version no');
const pp1 = good('docUpload', doc({ companyId: C1, docType: 'Passport', fileName: 'pp2025.pdf', subject: u1.UBOID, expiryDate: '2026-01-15' })).document;
const pp2 = good('docUpload', doc({ companyId: C1, docType: 'Passport', fileName: 'pp2026.pdf', subject: u1.UBOID, expiryDate: '2035-01-01' })).document;
dl = good('docList', { companyId: C1 }); eq(dl.documents.find(d => d.DocumentID === pp1.DocumentID).VersionStatus, 'Superseded', 'multi-type same subject superseded');
const bank1 = good('docUpload', doc({ companyId: C1, docType: 'Bank Statements', fileName: 'b1.pdf' })).document, bank2 = good('docUpload', doc({ companyId: C1, docType: 'Bank Statements', fileName: 'b2.pdf' })).document;
eq(good('docList', { companyId: C1 }).documents.filter(d => d.DocType === 'Bank Statements' && d.VersionStatus === 'Current').length, 2, 'multiple files per category');
const expired = good('docUpload', doc({ companyId: C1, docType: 'Tax Card', fileName: 'tax.pdf', expiryDate: '2020-01-01' }));
ok(expired.warnings.length > 0 && expired.document.EffStatus === 'Expired', 'expired doc flagged');
const stDoc = ctx.dbGet_('Documents', d2.DocumentID); const f = env.nodes[stDoc.DriveFileID];
ok(f && f.name.startsWith(d2.DocumentID) && env.nodes[stDoc.FolderID].name === 'Corporate Documents', 'stored in correct subfolder');
ok(env.nodes[ctx.dbGet_('Documents', expired.document.DocumentID).FolderID].name === 'Tax Documents', 'tax card -> Tax Documents');
const acc = good('docAccess', { docId: d2.DocumentID, mode: 'view' }); eq(Buffer.from(acc.base64, 'base64').toString(), '%PDF-1.4 test content', 'download content'); good('docAccess', { docId: d2.DocumentID, mode: 'download' });
bad('docSetStatus', { docId: d2.DocumentID, status: 'Verified' }, /permission/, 'auditor cannot verify');
as('aud2@firm.test'); bad('docDelete', { docId: d2.DocumentID, reason: 'x' }, /permission/, 'auditor cannot delete others\' docs');
as('aud1@firm.test'); good('docDelete', { docId: d2.DocumentID, reason: 'wrong file' }, 'auditor deletes own doc');
dl = good('docList', { companyId: C1 }); eq(dl.documents.find(d => d.DocumentID === d1.DocumentID).VersionStatus, 'Current', 'previous version restored after delete');
as('view@firm.test'); good('docList', { companyId: C1 }, 'viewer views docs'); bad('docUpload', doc({ companyId: C1, docType: 'Other Documents' }), /permission/, 'viewer cannot upload');
ok(good('companyGet', { id: C1 }).ubos[0].QIDNumber !== '12345678901', 'viewer sees masked QID');
as('mlro@firm.test'); good('docSetStatus', { docId: d1.DocumentID, status: 'Verified' }, 'MLRO verifies');
bad('docSetStatus', { docId: d1.DocumentID, status: 'Rejected' }, /Remarks/, 'reject needs remarks');
eq(good('companyGet', { id: C1 }).ubos.find(u => u.UBOID === u1.UBOID).QIDNumber, '12345678901', 'MLRO sees full QID');

section('Risk + KYC workflow (maker-checker)');
as('aud1@firm.test');
let k = good('kycGet', { companyId: C1 }); eq(k.review.Status, 'Draft', 'draft review exists');
ok(k.actions.includes('submit') && !k.actions.includes('approve'), 'auditor actions');
const RID = k.review.ReviewID;
bad('riskFinalize', { companyId: C1, rating: 'Low' }, /permission/, 'auditor cannot finalize risk');
let answers = {}; k = good('riskGet', { companyId: C1 }); k.config.factors.forEach(f => { answers[f.id] = f.options[0].v; });
Object.assign(answers, k.hints);
const rs = good('riskSave', { companyId: C1, answers }); ok(rs.complete, 'risk complete'); ok(['Low', 'Medium', 'High'].includes(rs.rating), 'risk rating computed ' + rs.rating);
const hi = good('riskSave', { companyId: C1, answers: Object.assign({}, answers, { sanctions: 'Potential match' }) }); eq(hi.rating, 'High', 'escalation flag forces High');
good('riskSave', { companyId: C1, answers });
bad('riskSave', { companyId: C1, answers: { pep: 'made up' } }, /Invalid answer/, 'invalid risk answer');
good('kycSubmit', { reviewId: RID }, 'submit');
eq(good('kycGet', { companyId: C1 }).review.Status, 'Submitted for Review', 'status after submit');
bad('kycApprove', { reviewId: RID }, /permission/, 'auditor cannot approve');
bad('companyUpdate', { id: C1, TradingName: 'Locked' }, /locked/, 'record locked during review');
bad('uboSave', { CompanyID: C1, FullName: 'New', Nationality: 'X', OwnershipPercentage: 1 }, /locked/, 'UBO add locked');
as('dmlro@firm.test'); good('kycStart', { reviewId: RID }, 'DMLRO starts review');
bad('kycApprove', { reviewId: RID }, /Approval blocked.*(Checklist|risk rating)/, 'approval blocked until requirements met');
bad('kycReject', { reviewId: RID, comments: '' }, /Comments are required/, 'reject requires comment');
good('riskFinalize', { companyId: C1, rating: 'Medium', reason: 'MLRO judgement' }, 'finalize risk with override');
const items = {}; k = good('kycGet', { companyId: C1 }); k.items.forEach(i => { items[i.id] = { done: true, comment: 'ok' }; });
good('kycSave', { reviewId: RID, items }, 'reviewer completes checklist');
k = good('kycGet', { companyId: C1 }); ok(k.issues.every(i => !/Checklist/.test(i)), 'checklist issue cleared');
bad('kycApprove', { reviewId: RID }, /Mandatory documents missing/, 'missing mandatory docs block approval');
as('aud1@firm.test');
for (const t of ['Trade License', 'Articles of Association (AOA)', 'Computer Card', 'Ownership Chart', 'Engagement Letter', 'Tax Card']) good('docUpload', doc({ companyId: C1, docType: t, fileName: t.replace(/\W/g, '') + '.pdf', expiryDate: '2035-01-01' }));
good('docUpload', doc({ companyId: C1, docType: 'QID', fileName: 'qid2.pdf', subject: r2.record.UBOID, expiryDate: '2035-01-01' }));
as('dmlro@firm.test');
good('kycApprove', { reviewId: RID, comments: 'fine' }, 'DMLRO approves');
const cA = good('companyGet', { id: C1 }); eq(cA.company.KycStatus, 'Approved', 'company approved'); eq(cA.company.RiskRating, 'Medium', 'final rating stored');
ok(cA.company.NextKycReviewDate > '2027-01-01', 'next review = +24 months for Medium: ' + cA.company.NextKycReviewDate); eq(cA.engagements[0].NextKycReviewDate, cA.company.NextKycReviewDate, 'engagement review dates updated');
as('aud1@firm.test'); bad('companyUpdate', { id: C1, TradingName: 'Sneaky' }, /approved/, 'auditor cannot modify approved record');
bad('kycSave', { reviewId: RID, items: {} }, /locked|permission/, 'checklist locked after approval');
good('docUpload', doc({ companyId: C1, docType: 'Other Documents', fileName: 'other.pdf' }), 'uploads still allowed after approval');
good('kycReopen', { companyId: C1, reason: 'Change of UBO' }, 'auditor re-opens (new review cycle)');
k = good('kycGet', { companyId: C1 }); eq(k.review.CycleNo, 2, 'new cycle'); eq(k.review.Status, 'Draft', 'new draft'); good('companyUpdate', { id: C1, TradingName: 'Now editable' }, 'editable after reopen');
// rejection loop + segregation
const RID2 = k.review.ReviewID; good('kycSubmit', { reviewId: RID2 });
as('owner@firm.test'); bad('kycStart', { reviewId: RID2 }, /permission/, 'sysadmin cannot review');
bad('docSetStatus', { docId: d1.DocumentID, status: 'Verified' }, /permission/, 'sysadmin cannot change document status');
bad('riskFinalize', { companyId: C1, rating: 'High', reason: 'x' }, /permission/, 'sysadmin cannot finalize risk');
as('mlro@firm.test'); good('kycStart', { reviewId: RID2 }); good('kycReject', { reviewId: RID2, comments: 'Need updated CR' }, 'MLRO rejects');
as('aud1@firm.test'); k = good('kycGet', { companyId: C1 }); eq(k.review.Status, 'Rejected', 'rejected'); good('kycSubmit', { reviewId: RID2 }, 'resubmit');
eq(good('kycGet', { companyId: C1 }).review.Status, 'Resubmitted', 'resubmitted');
// MLRO who submits cannot approve own
as('mlro@firm.test'); good('kycStart', { reviewId: RID2 }); good('kycReject', { reviewId: RID2, comments: 'again' });
good('kycReturn', { reviewId: RID2 }, 'return to auditor'); eq(good('kycGet', { companyId: C1 }).review.Status, 'Returned to Auditor', 'returned');
good('kycSubmit', { reviewId: RID2 }, 'MLRO (maker) resubmits'); bad('kycStart', { reviewId: RID2 }, /Segregation/, 'MLRO cannot review own submission');
as('dmlro@firm.test'); good('kycStart', { reviewId: RID2 }, 'other reviewer can');

section('Company delete/restore, sysadmin, settings');
as('mlro@firm.test'); bad('companyDelete', { id: C1 }, /reason/, 'delete needs reason'); good('companyDelete', { id: C1, reason: 'test' });
as('aud1@firm.test'); eq(good('companyList', {}).total, 0, 'deleted hidden'); bad('companyGet', { id: C1 }, /not found/, 'deleted not accessible to auditor');
bad('companyCreate', base, /deleted records/, 'dup detection includes deleted');
as('mlro@firm.test'); eq(good('companyList', { includeDeleted: true }).total, 1, 'MLRO sees deleted'); good('companyRestore', { id: C1 }); eq(good('companyList', {}).total, 1, 'restored');
as('aud1@firm.test'); bad('settingsSave', { key: 'RISK_CONFIG', value: {} }, /permission/, 'auditor cannot change settings');
as('mlro@firm.test'); bad('settingsSave', { key: 'REVIEW_FREQUENCY_MONTHS', value: { Low: 0, Medium: 1, High: 1 } }, /months/, 'settings validated');
good('settingsSave', { key: 'REVIEW_FREQUENCY_MONTHS', value: { Low: 36, Medium: 12, High: 6 } }, 'MLRO changes review frequency');
good('settingsSave', { key: 'FILE_RULES', value: { maxMB: 10, allowedExt: ['pdf', 'png'] } }, 'MLRO has full access incl. system settings');
as('dmlro@firm.test'); bad('settingsSave', { key: 'FILE_RULES', value: { maxMB: 5, allowedExt: ['pdf'] } }, /permission/, 'DMLRO cannot change system settings');
as('owner@firm.test'); bad('settingsSave', { key: 'FILE_RULES', value: { maxMB: 5, allowedExt: ['pdf', 'exe'] } }, /Executable/, 'exe blocked in settings'); good('settingsSave', { key: 'FILE_RULES', value: { maxMB: 5, allowedExt: ['pdf'] } });
bad('settingsSave', { key: 'RISK_CONFIG', value: {} }, /permission/, 'sysadmin cannot edit risk methodology');
const bkr = call('adminBackup'); if (!bkr.ok) console.log(ctx.dbAll_('Error_Log').slice(-1)[0]); const bk = bkr.data || {}; ok(/^AML_KYC_DB_Backup_\d{4}-\d{2}-\d{2}_\d{4}$/.test(bk.name), 'backup name ' + bk.name);
as('dmlro@firm.test'); bad('adminBackup', {}, /permission/, 'DMLRO has no technical backup right by default');

section('Dashboard, reports, search');
as('mlro@firm.test');
const dash = good('dashboard'); ok(dash.companies.total === 1 && typeof dash.documents.expired === 'number', 'dashboard counts');
const rep = good('reportRun', { type: 'companyKyc', companyId: C1 }); ok(rep.sections.length >= 8, 'company KYC report');
['docExpiry', 'highRisk', 'pendingReview', 'kycCompletion'].forEach(t => good('reportRun', { type: t }, 'report ' + t));
ok(good('reportPdf', { type: 'highRisk' }).mimeType === 'application/pdf', 'pdf export');
eq(good('search', { q: '12345678901' }).rows.length, 1, 'MLRO can search by QID'); as('view@firm.test'); eq(good('search', { q: '12345678901' }).rows.length, 0, 'viewer cannot search by QID');
bad('reportRun', { type: 'highRisk' }, /permission/, 'viewer no reports');

section('Audit trail');
as('owner@firm.test');
const al = good('auditList', {}); const acts = new Set(al.rows.map(r => r.Action));
['Company Created', 'Company Updated', 'UBO Added', 'UBO Updated', 'Document Uploaded', 'Document Replaced', 'Document Deleted', 'Risk Rating Changed', 'KYC Submitted', 'KYC Approved', 'KYC Rejected', 'User Created', 'Role Changed', 'Permission Denied', 'Company Deleted', 'Setting Changed', 'Database Backup', 'Document Downloaded', 'KYC Resubmitted']
  .forEach(a => { ok(acts.has(a), 'audit has ' + a); });
const ver = good('auditVerify'); ok(ver.ok && ver.checked > 50, 'hash chain valid over ' + ver.checked + ' entries');
const auditSheet = ss.getSheetByName('Audit_Log'); auditSheet.data[5][9] = 'tampered'; ctx.invalidate_('Audit_Log');
ok(!good('auditVerify').ok, 'tampering detected');
as('aud1@firm.test'); bad('auditList', {}, /permission/, 'auditor cannot view global log'); ok(call('auditList', { companyId: C1 }).ok, 'auditor views company history');
ok(!JSON.stringify(al.rows).includes('12345678901'), 'audit log does not contain full QID');

section('Restricted-access mode');
as('owner@firm.test'); const acc0 = ctx.getSetting_('ACCESS'); good('settingsSave', { key: 'ACCESS', value: Object.assign({}, acc0, { restrictToAssigned: true }) });
as('aud2@firm.test'); bad('companyGet', { id: C1 }, /not found/, 'unassigned auditor cannot open company'); eq(good('companyList', {}).total, 0, 'unassigned list empty');
as('aud1@firm.test'); good('companyGet', { id: C1 }, 'creator/assigned auditor can');
as('mlro@firm.test'); good('companyUpdate', { id: C1, AuthorizedUsers: 'aud2@firm.test' }); as('aud2@firm.test'); good('companyGet', { id: C1 }, 'authorised user can');

section('Test data helpers');
as('owner@firm.test'); ctx.resetMemo_(); const seeded = ctx.seedTestData(); ok(/Seeded/.test(seeded), 'seed test data: ' + seeded);
const before = ctx.dbAll_('Companies').length; const rm = ctx.removeTestData(); ok(/Removed 1/.test(rm), rm); eq(ctx.dbAll_('Companies').length, before - 1, 'test data removed');
ok(typeof ctx.dailyMaintenance() !== 'undefined', 'maintenance runs');

console.log('\n' + pass + ' passed, ' + failN + ' failed');
process.exit(failN ? 1 : 0);
